<a href="https://colab.research.google.com/github/ft10101/Basic-Programming-Problems/blob/main/First_day_with_python_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy #just to make sure numpy is installed.

**Adding two variables**

In [31]:
a = 10
b = 20
print(a+b)

30


**Creating 1D array**

In [33]:
import numpy as np #importing numpy as a variable np
a = np.array([1,2,3]) #creating 1D array using numpy as of just numeric array 
print(a) #prints array that's stored in variable a
a.shape #tells us the dimension of that array 

[1 2 3]


(3,)

**Creating 2D array**

In [34]:
b = np.array([(1,2,3,4),(5,6,7,8)])  #creating 2D array
print(b)  #printing 2D array saved in b
b.shape  #will tell you number of rows and columns of array

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

**2D Array of data type float**

In [38]:
c = np.array([(1,2,3),(4,5,6)],dtype=float)
#will create a 2D array of data type float
print(c)

[[1. 2. 3.]
 [4. 5. 6.]]


**Matrix of 0's only**

In [40]:
d = np.zeros((3,6),dtype=int)
#the two arguments here represent the dimension of the array that it will form of only zeros
print(d)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


**Matrix of 1's only**

In [41]:
e = np.ones((4,5)) #here 4*5 represents the dimensions of the matrix
print(e)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Matrix of a particular number**

In [45]:
f = np.full((5,4),3) #here the parameters have dimension size as 5*4 and 3 as that particular number
print(f)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


**Identity Matrix**

In [43]:
g = np.eye(4) #here 4 represents 4*4 matrix
print(g)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Random matrix between 0-1**

In [44]:
h = np.random.random((3,6)) #here random.random gives us numbers just between 0 and 1 only
print(h) #we specify 3*6 as the dimensions of the array

[[0.79835125 0.79201736 0.07680807 0.30620017 0.35155114 0.56003488]
 [0.24631959 0.98427972 0.95202685 0.35688031 0.20410364 0.98528273]
 [0.26041624 0.54689137 0.03008723 0.82393632 0.3768507  0.36053352]]


**Random generated array range and dimensions of array when given**

In [50]:
i = np.random.randint(10,100,(4,5)) # the first two parameters the range from 10 to100 and next(4,5) is for the dimension of array
print(i)

[[39 45 14 24 42]
 [46 83 90 92 95]
 [32 74 61 60 71]
 [52 58 61 68 69]]


**Array of evenly spaced values --> specifying no. of values required [linspace]**

In [51]:
j = np.linspace(10,30,5) #first two parameters give the range 10 to 30 and the last one gives no of outcomes we desire in between this range
print(j)

[10. 15. 20. 25. 30.]


**Array of evenly spaced calues --> specifying no. of steps [arange]**

In [53]:
k = np.arange(10,30,5) #first two parameters specify range and the last one no. of steps
print(k)

[10 15 20 25]


**Convert a list into a NumPy array**

In [57]:
list2 = [10,20,30] #defining a list2 with it's values 
print(list2) #printing list2
type(list2) #printing the data type of list2

[10, 20, 30]


list

In [58]:
np_array = np.array(list2) #converting list2 into numpy array
print(np_array) #printing np_array
type(np_array) #printing data type of np_array

[10 20 30]


numpy.ndarray

**Analyse NumPy Array**

In [62]:
print(c)

[[1. 2. 3.]
 [4. 5. 6.]]


In [59]:
print(c.shape) #shape gives us m*m / dimensions of matrix

(2, 3)


In [60]:
print(c.ndim) #ndim gives us dimension and gives only m in (m*m)

2


In [61]:
print(c.size) #size gives total number of elements

6


In [64]:
print(c.dtype) #dtype gives us the datatype of elements present

float64


**Array Manipulation**

In [66]:
array = np.random.randint(0,10,(2,3)) # 2*3 matrix of random numbers between 0 to 10 
print(array)
print(array.shape) # dimensions of array/matrix

[[2 5 2]
 [6 9 8]]
(2, 3)


**Transpose of a matrix**

In [67]:
trans = np.transpose(array) #transposing the 2*3 matrix into 3*2 matrix
print(trans)
print(trans.shape)

[[2 6]
 [5 9]
 [2 8]]
(3, 2)


**Reshaping Array**

In [68]:
a = np.random.randint(0,10,(2,3)) # generating random array of dimensions 2*3 elements range between 0 to 10
print(a)
print(a.shape)

[[9 2 0]
 [9 2 9]]
(2, 3)


In [70]:
b = a.reshape(3,2) #reshaping matrix a(2*3) into b matrix of dimensions 3*2
print(b)
print(b.shape)

[[9 2]
 [0 9]
 [2 9]]
(3, 2)
